name: CI


on:
  push:
      branches: [compiler]
  pull_request:
      branches: [compiler]

jobs:
  build:
    # FIXME: This builds with macOS 10.15. Move this to the 11.0 builders when possible. (See: https://github.com/actions/virtual-environments/issues/2486)
    runs-on:  macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: ./other/download_libs.sh

      - name: Build
        run: xcodebuild -project iina.xcodeproj -scheme iina CODE_SIGNING_ALLOWED=NO
      - name: Organize files
        id: organize
        run: |
          # cd /Users/runner/Library/Developer/Xcode/DerivedData/iina-csbkugdtxazzqogjnydbothqrvib/Build/Products/Debug
          zip -q -r -o Debug.zip /Users/runner/Library/Developer/Xcode/DerivedData/iina-csbkugdtxazzqogjnydbothqrvib/Build/Products/Debug
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "::set-output name=status::success"

      - name: Upload firmware directory
        uses: actions/upload-artifact@main
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: iina_firmware
          path: ${{ env.FIRMWARE }}
